# Generated by Django 5.1.4 on 2025-01-17 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('municipio_id', models.CharField(default='980', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Facturax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('forma_pago', models.CharField(default='1', max_length=2)),
                ('metodo_pago', models.CharField(default='10', max_length=2)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('VALIDADA', 'Validada'), ('ENVIADA', 'Enviada a DIAN'), ('ERROR', 'Error')], default='CREADA', max_length=20)),
                ('respuesta_dian', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturasapi.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_impuesto', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('tasa_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unidad_medida_id', models.IntegerField(default=70)),
                ('tributo_id', models.IntegerField(default=1)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturasapi.facturax')),
            ],
        ),
    ]
