productos = [
    {
        "nombre": "Filtro de aceite premium",
        "codigo": "FA-001",
        "descripcion": "Filtro de aceite de alta calidad para Toyota Corolla 2015.",
        "marca": "Toyota",
        "modelo": "Corolla",
        "anio": 2015,
        "categoria": "Filtros de aceite",
        "precio": Decimal('19.99'),
        "stock": 80,
        "en_oferta": True,
        "oferta_especial": False,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Amortiguador delantero",
        "codigo": "AD-002",
        "descripcion": "Amortiguador delantero para Honda Civic 2018.",
        "marca": "Honda",
        "modelo": "Civic",
        "anio": 2018,
        "categoria": "Suspensión",
        "precio": Decimal('49.99'),
        "stock": 40,
        "en_oferta": False,
        "oferta_especial": True,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Pastillas de freno",
        "codigo": "PF-003",
        "descripcion": "Pastillas de freno de larga duración para Nissan Altima 2017.",
        "marca": "Nissan",
        "modelo": "Altima",
        "anio": 2017,
        "categoria": "Frenos",
        "precio": Decimal('39.99'),
        "stock": 100,
        "en_oferta": True,
        "oferta_especial": False,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Filtro de aire deportivo",
        "codigo": "FA-004",
        "descripcion": "Filtro de aire deportivo para BMW 3 Series 2020.",
        "marca": "BMW",
        "modelo": "3 Series",
        "anio": 2020,
        "categoria": "Filtros de aire",
        "precio": Decimal('29.99'),
        "stock": 60,
        "en_oferta": True,
        "oferta_especial": True,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Sensor de oxígeno",
        "codigo": "SO-005",
        "descripcion": "Sensor de oxígeno compatible con Ford F-150 2015.",
        "marca": "Ford",
        "modelo": "F-150",
        "anio": 2015,
        "categoria": "Electrónica",
        "precio": Decimal('59.99'),
        "stock": 25,
        "en_oferta": False,
        "oferta_especial": True,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Aceite de motor sintético",
        "codigo": "AM-006",
        "descripcion": "Aceite de motor sintético de alto rendimiento para Chevrolet Camaro 2016.",
        "marca": "Chevrolet",
        "modelo": "Camaro",
        "anio": 2016,
        "categoria": "Lubricantes",
        "precio": Decimal('35.99'),
        "stock": 150,
        "en_oferta": True,
        "oferta_especial": False,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Kit de faros LED",
        "codigo": "FL-007",
        "descripcion": "Faros LED de alta intensidad para Jeep Wrangler 2019.",
        "marca": "Jeep",
        "modelo": "Wrangler",
        "anio": 2019,
        "categoria": "Carrocería",
        "precio": Decimal('99.99'),
        "stock": 30,
        "en_oferta": True,
        "oferta_especial": True,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Cargador de batería portátil",
        "codigo": "CB-008",
        "descripcion": "Cargador de batería compacto para Tesla Model S 2018.",
        "marca": "Tesla",
        "modelo": "Model S",
        "anio": 2018,
        "categoria": "Electrónica",
        "precio": Decimal('79.99'),
        "stock": 20,
        "en_oferta": False,
        "oferta_especial": True,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Escobillas limpiaparabrisas",
        "codigo": "EL-009",
        "descripcion": "Juego de escobillas para Mazda CX-5 2017.",
        "marca": "Mazda",
        "modelo": "CX-5",
        "anio": 2017,
        "categoria": "Accesorios",
        "precio": Decimal('24.99'),
        "stock": 100,
        "en_oferta": True,
        "oferta_especial": False,
        "imagen": "media/repuesto/auto.png"
    },
    {
        "nombre": "Filtro de combustible",
        "codigo": "FC-010",
        "descripcion": "Filtro de combustible de alta eficiencia para Volkswagen Passat 2015.",
        "marca": "Volkswagen",
        "modelo": "Passat",
        "anio": 2015,
        "categoria": "Filtros de combustible",
        "precio": Decimal('14.99'),
        "stock": 120,
        "en_oferta": True,
        "oferta_especial": False,
        "imagen": "media/repuesto/auto.png"
    }
    # Agregar 10 más siguiendo el formato
    ]


