# Generated by Django 5.1.4 on 2025-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='Internet', max_length=40, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=17, null=True)),
                ('vehicle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_cliente', models.CharField(blank=True, max_length=80, null=True)),
                ('vehicle_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('distribuidorax', models.CharField(blank=True, max_length=400, null=True)),
                ('costAbonado', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('costotal', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('problem_description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Consulta', 'Consulta'), ('Pendiente en llegar', 'Pendiente en llegar'), ('Pendiente de investigar', 'Pendiente de investigar'), ('Pendiente de enviar', 'Pendiente de enviar'), ('Compra no entregada', 'Compra no entregada'), ('Compra entregada', 'Compra entregada')], default='Consulta', max_length=50, null=True)),
                ('dinomoDis', models.CharField(choices=[('Sin estado', 'Sin estado'), ('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Monto pagado', 'Monto pagado'), ('Monto pendiente', 'Monto pendiente')], default='Sin estado', max_length=50, null=True)),
            ],
        ),
    ]
