# Generated by Django 5.1.4 on 2025-01-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_blog', models.CharField(max_length=255, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('slug_blog', models.SlugField(blank=True, max_length=255, unique=True)),
                ('resumen_blog', models.TextField()),
                ('caracteristica_blog', models.TextField()),
                ('explicacion_blog', models.TextField()),
                ('youtube_blog', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_blog', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen_blog', models.ImageField(blank=True, null=True, upload_to='blogs/')),
            ],
        ),
    ]
