# Generated by Django 5.1.4 on 2024-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_fecha_modificado_blog_slug_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
