# Generated by Django 5.1.4 on 2025-02-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_document_id', models.CharField(max_length=100)),
                ('identification', models.CharField(max_length=100)),
                ('dv', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('names', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('legal_organization_id', models.IntegerField()),
                ('tribute_id', models.IntegerField()),
                ('municipality_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('discount_rate', models.FloatField()),
                ('price', models.FloatField()),
                ('tax_rate', models.CharField(max_length=10)),
                ('unit_measure_id', models.IntegerField()),
                ('standard_code_id', models.IntegerField()),
                ('is_excluded', models.IntegerField()),
                ('tribute_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbering_range_id', models.IntegerField(blank=True, null=True)),
                ('reference_code', models.CharField(max_length=100, unique=True)),
                ('observation', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_form', models.IntegerField(default=1)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('payment_method_code', models.IntegerField(default=10)),
                ('billing_period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factus.billingperiod')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factus.customer')),
                ('items', models.ManyToManyField(to='factus.item')),
            ],
        ),
        migrations.CreateModel(
            name='WithholdingTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('withholding_tax_rate', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withholding_taxes', to='factus.item')),
            ],
        ),
    ]
