# Generated by Django 5.1.4 on 2024-12-25 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0005_remove_carrito_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['slug'], name='tiendas_tie_slug_dd0fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['propietario'], name='tiendas_tie_propiet_8d4fc7_idx'),
        ),
    ]
